version: '3'

services:

  site:
    build:
      dockerfile: Docker/Dockerfile
      context: .
    depends_on:
      - database
    ports:
      - "8000:8000"
    volumes:
      - ${PWD}:/code/

  database:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pkbcilwl
      POSTGRES_DB: pzlamsite
    volumes:
      - ${PWD}/database-init:/docker-entrypoint-initdb.d/
    expose:
      - "5432"