version: '3'

services:

  site:
    build:
      dockerfile: Docker/Dockerfile
      context: .
    depends_on:
      - database
    ports:
      - "8000:8000"

  database:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_USER: pzlam
      POSTGRES_PASSWORD: pkbcilwl
      POSTGRES_DB: pzlamsite
    expose:
      - "5432"